# Generated by Django 2.2.3 on 2019-07-06 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='deleted_on',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='modified_on',
        ),
    ]
