# Generated by Django 2.2.3 on 2019-07-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0002_auto_20190706_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='description',
            field=models.CharField(default='something', max_length=1024),
            preserve_default=False,
        ),
    ]
